use customer_shopping_behaviour;

-- Alter TABLE customer_shopping_behaviour_table MODIFY subscription_status VARCHAR(3);
-- UPDATE customer_shopping_behaviour_table SET subscription_status = 'Yes' where subscription_status = '1';
-- UPDATE customer_shopping_behaviour_table SET subscription_status = 'No' where subscription_status = '0';


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
	gender,
	SUM(purchase_amount_USD) AS total_revenue
FROM customer_shopping_behaviour_table
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average 
--     purchase amount?
SELECT
	customer_id,
    SUM(purchase_amount_USD) as total_spend
FROM customer_shopping_behaviour_table
WHERE discount_applied IS TRUE
GROUP BY customer_id
HAVING total_spend > (SELECT AVG(purchase_amount_USD) 
					  FROM customer_shopping_behaviour_table);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
	item_purchased AS products,
    ROUND(AVG(review_rating), 2) AS average_rating
FROM customer_shopping_behaviour_table
GROUP BY products
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
	shipping_type,
    ROUND(AVG(purchase_amount_USD), 2) AS avg_purchase_amount
FROM customer_shopping_behaviour_table
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--     between subscribers and non-subscribers.
SELECT
	subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount_USD), 2) AS avg_spend,
    SUM(purchase_amount_USD) AS total_revenue
FROM customer_shopping_behaviour_table
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--     (This was a bit tricky to solve)
SELECT
    item_purchased,
    ROUND(COUNT(CASE WHEN discount_applied IS TRUE THEN 1 END) * 100.0 
		   / COUNT(*), 2) AS discount_rate
FROM customer_shopping_behaviour_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number 
--     of previous purchases, and show the count of each segment.
WITH customer_per_segements AS(
	SELECT
		customer_id,
        previous_purchases,
		CASE 
			WHEN previous_purchases > 10 THEN 'Loyal'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'New'
		END AS customer_segements
	FROM customer_shopping_behaviour_table
)
SELECT
	customer_segements,
    COUNT(customer_id) AS total_customers
FROM customer_per_segements
GROUP BY customer_segements;

-- Q8. What are the top 3 most purchased products within each category?
WITH ranked AS (
	SELECT
		category,
		item_purchased AS products,
        COUNT(customer_id) AS total_orders,
		DENSE_RANK()
		    OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS top_purchased
FROM customer_shopping_behaviour_table
GROUP BY category, products
)
SELECT * FROM ranked
WHERE top_purchased <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also 
--     likely to subscribe?
SELECT
	subscription_status,
    COUNT(customer_id)  AS repeat_buyers
FROM customer_shopping_behaviour_table
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT
	age_group,
    SUM(purchase_amount_USD)  AS total_revenue,
    ROUND((SUM(purchase_amount_USD)
    / (SELECT SUM(purchase_amount_USD) 
       FROM customer_shopping_behaviour_table)) * 100, 2) AS total_revenue_percentage
FROM customer_shopping_behaviour_table
GROUP BY age_group
ORDER BY total_revenue_percentage DESC;













